name: C++ CI/CD with Make

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAKEFLAGS: "--debug=b"
      MAKELEVEL: 0

    steps:
      - name: Set up GCC
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y g++-9

      - name: Check GCC Version
        run: g++ --version

      - name: Enable debug
        run: |
          echo "MAKEFLAGS=$MAKEFLAGS" >> $GITHUB_ENV
          echo "MAKELEVEL=$MAKELEVEL" >> $GITHUB_ENV
        shell: bash

      - name: Build
        run: make
        working-directory: ${{ github.workspace }}  # Set the working directory to the repository root

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Repository Contents
        run: |
          ls -al
          ls -al src
          cat Makefile

      - name: Build with Make
        run: make
        working-directory: ${{ github.workspace }}  # Set the working directory to the repository root

      - name: Set up Catch2
        run: |
          git submodule update --init --recursive

      - name: Run Tests
        run: make test
        working-directory: ${{ github.workspace }}  # Set the working directory to the repository root

      - name: Display Artifacts
        run: |
          ls -al build
        working-directory: ${{ github.workspace }}  # Set the working directory to the repository root

      - name: Deploy (Example)
        if: success()
        run: echo "Deployment step (replace with actual deployment commands)"

      - name: Debug Statement
        if: failure() || cancelled()
        run: echo "The workflow failed or was cancelled."
