name: C++ CI/CD with Make

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print Repository Contents
      run: |
        ls -al
        ls -al src
        cat Makefile

    - name: Build with Make
      run: |
        make

    - name: Run Tests
      run: |
        make test

    - name: Display Artifacts
      run: |
        ls -al build

    - name: Deploy (Example)
      if: success()
      run: echo "Deployment step (replace with actual deployment commands)"

    - name: Debug Statement
      if: failure() || cancelled()
      run: echo "The workflow failed or was cancelled."
