name: C++ CI/CD with Make and Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Repository Contents
        run: |
          ls -al
          ls -al src
          cat Makefile

      - name: Set up GCC
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y g++-9

      - name: Check GCC Version
        run: g++ --version

      - name: Change Directory
        run: cd $GITHUB_WORKSPACE

      - name: Print Current Directory
        run: pwd

      - name: Build
        run: make -f Makefile

      - name: Set up Catch2
        run: git submodule update --init --recursive

      - name: Run Tests
        run: make -f Makefile test

      - name: Display Artifacts
        run: ls -al build

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
          docker build -t ghcr.io/babak2/my-app:latest .
          docker push ghcr.io/babak2/my-app:latest

      - name: Deploy (Example)
        if: success()
        run: echo "Deployment step (replace with actual deployment commands)"

      - name: Debug Statement
        if: failure() || cancelled()
        run: echo "The workflow failed or was cancelled."

